name: scalafmt-native-action
description: GitHub action to run scalafmt-native.
author: jrouly
inputs:
  version:
    description: The scalafmt-native version to run.
    default: 3.5.8
    required: false
  arguments:
    description: Arguments to pass to scalafmt-native.
    default: '--list'
    required: false
branding:
  icon: 'code'
  color: 'gray-dark'
runs:
  using: node16
  main: dist/index.js
